networks:
  default:
    driver: bridge
    name: roboshop # incase not created not mention external
    external: true # as i created network already outside compose manually so it is true.
services:
  mongodb:
    image: obulanaidu/mongodb:v1
    container_name: mongodb
  catalogue:
    image: obulanaidu/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: obulanaidu/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: obulanaidu/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: obulanaidu/mysql:v1
    container_name: mysql
  shipping:
    image: obulanaidu/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  # payment:
  #   image: obulanaidu/payment:v1
  #   container_name: payment
  #   - user
  #   - cart
  #   - rabbitmq
  