networks:
  default:
    driver: bridge
    name: roboshop # external=true if created manually docker network create roboshop
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq: #equal to docker volume create rabbitmq
services:
  mongodb:
    image: obulanaidu/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: obulanaidu/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: obulanaidu/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: obulanaidu/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: obulanaidu/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: obulanaidu/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - mysql:/var/lib/rabbitmq
  payment:
    image: obulanaidu/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - user
    - cart
    - rabbitmq
  frontend:
    image: obulanaidu/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
  